cp alchemy.x	alchemy
cp analyze.x	analyze
cp anneal.x	anneal
cp archive.x	archive
cp bar.x	bar
cp correlate.x	correlate
cp crystal.x	crystal
cp diffuse.x	diffuse
cp distgeom.x	distgeom
cp document.x	document
cp dynamic.x	dynamic
cp gda.x	gda
cp intedit.x	intedit
cp intxyz.x	intxyz
cp minimize.x	minimize
cp minirot.x	minirot
cp minrigid.x	minrigid
cp molxyz.x	molxyz
cp monte.x	monte
cp newton.x	newton
cp newtrot.x	newtrot
cp nucleic.x	nucleic
cp optimize.x	optimize
cp optirot.x	optirot
cp optrigid.x	optrigid
cp path.x	path
cp pdbxyz.x	pdbxyz
cp polarize.x	polarize
cp poledit.x	poledit
cp potential.x	potential
cp prmedit.x	prmedit
cp protein.x	protein
cp pssrigid.x	pssrigid
cp pssrot.x	pssrot
cp pss.x	pss
cp radial.x	radial
cp saddle.x	saddle
cp scan.x	scan
cp sniffer.x	sniffer
cp spacefill.x	spacefill
cp spectrum.x	spectrum
cp superpose.x	superpose
cp sybylxyz.x	sybylxyz
cp testgrad.x	testgrad
cp testhess.x	testhess
cp testpair.x	testpair
cp testpol.x	testpol
cp testrot.x	testrot
cp timerot.x	timerot
cp timer.x	timer
cp torsfit.x	torsfit
cp valence.x	valence
cp vibbig.x	vibbig
cp vibrate.x	vibrate
cp vibrot.x	vibrot
cp xtalfit.x	xtalfit
cp xtalmin.x	xtalmin
cp xyzedit.x	xyzedit
cp xyzint.x	xyzint
cp xyzpdb.x	xyzpdb
cp xyzsybyl.x	xyzsybyl
